project:
  name: quickstart-amazon-eks
  owner: quickstart-eng@amazon.com
  shorten_stack_name: true
  regions:
    - af-south-1
    - ap-east-1
    - ap-northeast-1
    - ap-northeast-2
    - ap-northeast-3
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ap-southeast-3
    - ca-central-1
    - eu-central-1
    - eu-north-1
    - eu-south-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - me-south-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - us-gov-east-1
    - us-gov-west-1
    - cn-north-1
    - cn-northwest-1
  template: templates/amazon-eks-entrypoint-new-vpc.template.yaml
  parameters:
    RemoteAccessCIDR: disabled-onlyssmaccess
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
tests:
  defaults:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
    regions:
      - me-south-1
  v1-22:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      KubernetesVersion: '1.22'
    regions:
      - us-east-1
  v1-21:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      KubernetesVersion: '1.21'
    regions:
      - us-east-2
  v1-20:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      KubernetesVersion: '1.20'
    regions:
      - us-west-2
  public-endpoint:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EKSPublicAccessEndpoint: Enabled
      ProvisionBastionHost: Disabled
      ALBIngressController: Disabled
    regions:
      - ap-northeast-2
  cluster-autoscaler:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ClusterAutoScaler: Enabled
      NodeGroupType: 'Unmanaged'
      ALBIngressController: Disabled
    regions:
      - eu-central-1
  managed-node-group:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ClusterAutoScaler: Disabled
      EKSPublicAccessEndpoint: Enabled
      ALBIngressController: Disabled
    regions:
      - ap-south-1
  monitoring-prom-graf:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      PrometheusIntegration: Enabled
      GrafanaIntegration: Enabled
      EKSPublicAccessEndpoint: Enabled
      NodeGroupType: 'Unmanaged'
      ALBIngressController: Disabled
    regions:
      - ap-southeast-2
  2az:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: "2"
      EKSPublicAccessEndpoint: Enabled
      NodeGroupType: 'Unmanaged'
      ProvisionBastionHost: Disabled
    regions:
      - cn-north-1
  govcloud:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
    regions:
      - us-gov-east-1
      - us-gov-west-1
  no-logging:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: "2"
      EKSClusterLoggingTypes: ""
      EKSPublicAccessEndpoint: Enabled
      NodeGroupType: 'Unmanaged'
      ALBIngressController: Disabled
    regions:
      - eu-west-2
  with-hybrid:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EKSPublicAccessEndpoint: Enabled
      NodeGroupType: 'Unmanaged'
      ALBIngressController: Disabled
    regions:
      - us-west-2
  load-balancer-controller:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      NodeGroupType: 'Unmanaged'
    regions:
      - us-east-2
  fargate:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ClusterAutoScaler: Enabled
      FargateNamespaces: kube-system
      FargateLabels: 'app.kubernetes.io/name=aws-cluster-autoscaler'
      EKSPublicAccessEndpoint: Enabled
      NodeGroupType: 'Unmanaged'
      ALBIngressController: Enabled
    regions:
      - us-east-1
  enable-oidc:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      IamOidcProvider: Enabled
      EKSPublicAccessEndpoint: Enabled
      NodeGroupOS: Bottlerocket
      NodeInstanceFamily: ARM
      NodeInstanceType: c6g.medium
      NodeGroupType: 'Unmanaged'
      ALBIngressController: Enabled
    regions:
      - eu-west-1
  snyk:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EKSPublicAccessEndpoint: Enabled
      SnykIntegration: Enabled
      SnykIntegrationId: ---overridden---
      ALBIngressController: Enabled
    regions:
      - eu-west-3
  new-relic:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EKSPublicAccessEndpoint: Enabled
      NewRelicIntegration: Enabled
      NewRelicLicenseKey: ---overridden---
      ALBIngressController: Enabled
    regions:
      - sa-east-1
  rancher:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EKSPublicAccessEndpoint: Enabled
      RancherIntegration: Enabled
      ALBIngressController: Enabled
    regions:
      - ap-east-1
  managed-node-group-ASC:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ClusterAutoScaler: Enabled
      TestSuite: Enabled
      ProvisionBastionHost: Disabled
      ALBIngressController: Enabled
    regions:
      - af-south-1
  windows:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      TestSuite: Enabled
      NodeGroupOS: Windows
      NodeGroupType: 'Unmanaged'
      ALBIngressController: Enabled
    regions:
      - eu-north-1
  # # Disabled due to interop
  # vault:
  #   parameters:
  #     AvailabilityZones: $[taskcat_genaz_3]
  #     ALBIngressController: Enabled
  #     VaultIntegration: Enabled
  #     VaultUIDomainName: ---overridden---
  #     VaultUIHostedZoneID: ---overridden---
  #   regions:
  #     - eu-north-1
  # # Disabled due to interop
  # consul:
  #   parameters:
  #     AvailabilityZones: $[taskcat_genaz_3]
  #     ALBIngressController: Enabled
  #     ConsulIntegration: Enabled
  #     ConsulUIDomainName: ---overridden---
  #     ConsulUIHostedZoneID: ---overridden---
  #   regions:
  #     - eu-west-1
  calico:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      NodeGroupType: 'Unmanaged'
      ALBIngressController: Disabled
      CalicoIntegration: Enabled
    regions:
      - us-west-2
  rafaysystems:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      NodeGroupType: 'Unmanaged'
      ALBIngressController: Disabled
      RafaySysIntegration: Enabled
      RafaySysFirstName: override
      RafaySysLastName: override
      RafaySysOrganizationName: override
      RafaySysEmail: override
    regions:
      - ca-central-1
  spot:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      NodeGroupType: Unmanaged
      OnDemandPercentage: 0
      OnDemandBastionPercentage: 0
    regions:
      - us-east-1
