AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys an EKS cluster with MLRun Kit in a new VPC
Metadata:
  AutoInstance:
    NodeInstanceType:
      InstanceFilters:
      - [['PV'], "!=", "SupportedVirtualizationTypes"]
  QuickStartDocumentation:
    EntrypointName: "Launch into a new VPC"
    Order: Index a
  LintSpellExclude:
    - Kubernetes
    - ARNs
    - Resource Names
    - autoscaler
    - IOPS
    - EfsStorageClass
    - Lambda
    - maxIO
    - Resource Name
    - Enabled
    - Disabled
    - Prometheus
    - Encrypt
    - Fargate
    - namespace
    - Snyk
    - Security
    - New Relic
    - APN
    - '"No"'
    - Windows
    - '"Config '
    - '(Optional)'
    - Unmanaged
    - Node
    - NewRelicIntegration
    - Integration
    - Auto Scaling
    - Partner
    - Vault
    - Consul
    - HashiCorp
    - CalicoIntegration
    - RafaySysIntegration
    - RafaySysProject
    - RafaySysBootstrapBucket
    - RafaySysBootstrapKey
    - RafaySysApiKey
    - RafaySysApiSecret
    - RafaySysFirstName
    - RafaySysLastName
    - RafaySysOrganizationName
    - RafaySysEmail
    - Rafay Systems
    - Rafay
    - Rancher
    - yaml
    - rafay
    - DomainName
    - Hosted
    - Domain Name
    - Domain name
    - Grafana
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General configuration
        Parameters:
          - EKSClusterName
      - Label:
          default: VPC network configuration
        Parameters:
          - NumberOfAZs
          - AvailabilityZones
          - RemoteAccessCIDR
      - Label:
          default: Amazon EKS configuration
        Parameters:
          - AdditionalEKSAdminUserArn
          - NodeInstanceType
          - NumberOfNodes
          - NodeGroupOS
          - NodeInstanceFamily
      - Label:
          default: Amazon EC2 configuration
        Parameters:
          - KeyPairName
          - ProvisionBastionHost
      - Label:
          default: Iguazio MLRun configuration
        Parameters:
          - ClusterDomain
          - RegistryDomainName
          - RegistrySuffix
          - RegistryUsername
          - RegistryPassword
          - RegistryEmail
      - Label:
          default: Debugging options
        Parameters:
          - DeployMLRunKit
          - MLrunKitVersion
    ParameterLabels:
      AvailabilityZones:
        default: Availability Zones
      KeyPairName:
        default: SSH key name
      RemoteAccessCIDR:
        default: Allowed external access CIDR
      NodeInstanceType:
        default: Instance type
      NumberOfNodes:
        default: Number of nodes
      MaxNumberOfNodes:
        default: Maximum number of nodes
      AdditionalEKSAdminUserArn:
        default: Additional EKS admin ARN (IAM user)
      NumberOfAZs:
        default: Number of Availability Zones
      ProvisionBastionHost:
        default: Provision bastion host
      EKSClusterName:
        default: EKS cluster name
      NodeGroupType:
        default: Node group type
      NodeInstanceFamily:
        default: Node instance family
      NodeGroupOS:
        default: Node group OS
      ClusterDomain:
        default: Route 53 hosted DNS domain
      RegistryDomainName:
        default: Container registry URL
      RegistrySuffix:
        default: Container registry suffix
      RegistryUsername:
        default: Container registry username
      RegistryPassword:
        default: Container registry password
      RegistryEmail:
        default: Container registry user's email address
      DeployMLRunKit:
        default: Deploy MLRun Kit
      MLrunKitVersion:
        default: MLRun Kit version
Parameters:
  AvailabilityZones:
    Description: List of Availability Zones to use for the subnets in the VPC. The number of selected entries should match the value entered for Number of Availability Zones parameter.
    Type: List<AWS::EC2::AvailabilityZone::Name>
  KeyPairName:
    Description: Name of an existing key pair, which allows to securely connect to EC2 instance after they launch.
    Type: AWS::EC2::KeyPair::KeyName
  RemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: CIDR IP range that is permitted to access the instances. We recommend
      that you set this value to a trusted IP range.
    Type: String
  AdditionalEKSAdminUserArn:
    Default: ""
    Description: "(Optional) IAM user ARN to be granted administrative access to the EKS cluster."
    Type: String
  NodeInstanceType:
    Default: m5.2xlarge
    AllowedValues: ['t3.large', 't3.xlarge', 't3.2xlarge', 't3a.large', 't3a.xlarge', 't3a.2xlarge', 't2.large', 't2.xlarge', 't2.2xlarge', 'm5.large', 'm5.xlarge', 'm5.2xlarge', 'm5.4xlarge', 'm5.8xlarge', 'm5.12xlarge', 'm5.16xlarge', 'm5.24xlarge', 'm5a.large', 'm5a.xlarge', 'm5a.2xlarge', 'm5a.4xlarge', 'm5a.8xlarge', 'm5a.12xlarge', 'm5a.16xlarge', 'm5a.24xlarge', 'm5n.large', 'm5n.xlarge', 'm5n.2xlarge', 'm5n.4xlarge', 'm5n.8xlarge', 'm5n.12xlarge', 'm5n.16xlarge', 'm5n.24xlarge', 'm5zn.large', 'm5zn.xlarge', 'm5zn.2xlarge', 'm5zn.3xlarge', 'm5zn.6xlarge', 'm5zn.12xlarge', 'm4.large', 'm4.xlarge', 'm4.2xlarge', 'm4.4xlarge', 'm4.10xlarge', 'm4.16xlarge', 'c5.large', 'c5.xlarge', 'c5.2xlarge', 'c5.4xlarge', 'c5.9xlarge', 'c5.12xlarge', 'c5.18xlarge', 'c5.24xlarge', 'c5a.large', 'c5a.xlarge', 'c5a.2xlarge', 'c5a.4xlarge', 'c5a.9xlarge', 'c5a.12xlarge', 'c5a.18xlarge', 'c5a.24xlarge', 'c5n.large', 'c5n.xlarge', 'c5n.2xlarge', 'c5n.4xlarge', 'c5n.9xlarge', 'c5n.12xlarge', 'c5n.18xlarge', 'c4.large', 'c4.xlarge', 'c4.2xlarge', 'c4.4xlarge', 'c4.8xlarge', 'r5.large', 'r5.xlarge', 'r5.2xlarge', 'r5.4xlarge', 'r5.8xlarge', 'r5.12xlarge', 'r5.16xlarge', 'r5.24xlarge', 'r5a.large', 'r5a.xlarge', 'r5a.2xlarge', 'r5a.4xlarge', 'r5a.8xlarge', 'r5a.12xlarge', 'r5a.16xlarge', 'r5a.24xlarge', 'r5n.large', 'r5n.xlarge', 'r5n.2xlarge', 'r5n.4xlarge', 'r5n.8xlarge', 'r5n.12xlarge', 'r5n.16xlarge', 'r5n.24xlarge', 'r4.large', 'r4.xlarge', 'r4.2xlarge', 'r4.4xlarge', 'r4.8xlarge', 'r4.16xlarge', 'x1e.large', 'x1e.xlarge', 'x1e.2xlarge', 'x1e.4xlarge', 'x1e.8xlarge', 'x1e.16xlarge', 'x1e.32xlarge', 'x1.16xlarge', 'x1.32xlarge', 'p3.2xlarge', 'p3.8xlarge', 'p3.16xlarge', 'p3.24xlarge', 'p2.xlarge', 'p2.8xlarge', 'p2.16xlarge', 'g4dn.xlarge', 'g4dn.2xlarge', 'g4dn.4xlarge', 'g4dn.8xlarge', 'g4dn.12xlarge', 'g4dn.16xlarge', 'g4dn.2xlarge', 'g4ad.4xlarge', 'g4ad.8xlarge', 'g4ad.16xlarge', 'g3s.xlarge', 'g3.4xlarge', 'g3.8xlarge', 'g3.16xlarge']
    ConstraintDescription: Must be a valid EC2 instance type. 
    Description: EC2 instance type.
    Type: String
  NumberOfNodes:
    Default: 3
    Description: Number of Amazon EKS node instances. The default is one for each of the three Availability Zones.
    Type: Number
  NumberOfAZs:
    Type: String
    AllowedValues: ["2", "3"]
    Default: "3"
    Description: Number of Availability Zones to use in the VPC. A Minimum of 2
      Availability Zones are required for this deployment.
  ProvisionBastionHost:
    Type: String
    AllowedValues: [ "Enabled", "Disabled" ]
    Default: "Disabled"
    Description: Create a bastion host with a public IP to allow ssh access to the EKS EC2 instances.
  EKSClusterName:
    Type: String
    AllowedPattern: "[a-z0-9][a-z0-9-]{0,61}[a-z0-9]"
    Description: "Name for the EKS cluster."
    ConstraintDescription: Can contain lower-case letters, numbers and hyphens (a hyphen may not be the first or last character)."
  NodeInstanceFamily:
    Default: Standard
    AllowedValues: ['Standard', 'GPU']
    Type: String
    Description: Choose the instance family to match the value of "Node instance type."
  ClusterDomain:
    Description: "The EKS cluster DNS record will be added to this domain."
    Type: String
    MinLength: 1
  RegistryDomainName:
    Description: Registry for Nuclio container images
    Type: String
    Default: index.docker.io
    MinLength: 1
  RegistrySuffix:
    Description: Container registry suffix, for example /v1/
    Type: String
    Default: /v1/
    AllowedPattern: ^$|^/.*/
    ConstraintDescription: Container registry suffix should be either empty or start and end with a slash /.
  RegistryUsername:
    Type: String
    MinLength: 1
  RegistryPassword:
    Type: String
    MinLength: 1
    NoEcho: true
  RegistryEmail:
    MinLength: 1
    Type: String
  DeployMLRunKit:
    Description: Deploy MLRun Kit
    Default: yes
    Type: String
    AllowedValues: [yes, no]
  MLrunKitVersion:
    Type: String
    Default: ""
Mappings:
  Config:
    QSS3KeyPrefix: { Value: quickstart-amazon-eks/ }
    QSS3BucketRegion: { Value: us-east-2 }
    EKSPublicAccessEndpoint: { Value: Enabled }
    ALBIngressController: { Value: Enabled }
    NodeGroupType: { Value: Managed }
    KubernetesVersion: { Value: 1.22 }
    QSS3BucketName: { Value: mlk-alexp-122 }
Conditions:
  DeployNvidiaPlugin: !Equals 
    - !Ref NodeInstanceFamily
    - GPU
  DeployMLRunStack: !Equals
    - !Ref DeployMLRunKit
    - yes
Resources:
  AdvancedConfigDefaultsStack:
    Type: AWS::CloudFormation::Stack
    Metadata: { cfn-lint: { config: { ignore_checks: [E9902, W9901] } } }
    Properties:
      TemplateURL: !Sub
        - 'https://${QSS3BucketName}.s3.${QSS3BucketRegion}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/amazon-eks-advanced-configuration.template.yaml'
        - QSS3BucketName: !FindInMap [ Config, QSS3BucketName, Value ]
          QSS3BucketRegion: !FindInMap [ Config, QSS3BucketRegion, Value ]
          QSS3KeyPrefix: !FindInMap [ Config, QSS3KeyPrefix, Value ]
      Parameters:
        ConfigSetName: !Ref AWS::StackName
        KubernetesVersion: !FindInMap [ Config, KubernetesVersion, Value ]
  EKSNewVPC:
    Type: AWS::CloudFormation::Stack
    DependsOn: AdvancedConfigDefaultsStack
    Properties:
      TemplateURL: !Sub
        - 'https://${QSS3BucketName}.s3.${QSS3BucketRegion}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/amazon-eks-entrypoint-new-vpc.template.yaml'
        - QSS3BucketName: !FindInMap [ Config, QSS3BucketName, Value ]
          QSS3BucketRegion: !FindInMap [ Config, QSS3BucketRegion, Value ]
          QSS3KeyPrefix: !FindInMap [ Config, QSS3KeyPrefix, Value ]
      Parameters:
        ConfigSetName: !Ref AWS::StackName
        AvailabilityZones: !Join [ ',', !Ref 'AvailabilityZones' ]
        KeyPairName: !Ref KeyPairName
        QSS3BucketName: !FindInMap [ Config, QSS3BucketName, Value ]
        QSS3BucketRegion: !FindInMap [ Config, QSS3BucketRegion, Value ]
        QSS3KeyPrefix: !FindInMap [ Config, QSS3KeyPrefix, Value ]
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        EKSPublicAccessEndpoint: !FindInMap [Config, EKSPublicAccessEndpoint, Value]
        AdditionalEKSAdminUserArn: !Ref AdditionalEKSAdminUserArn
        NodeInstanceType: !Ref NodeInstanceType
        NumberOfNodes: !Ref NumberOfNodes
        MaxNumberOfNodes: !Ref NumberOfNodes
        NumberOfAZs: !Ref NumberOfAZs
        ProvisionBastionHost: !Ref ProvisionBastionHost
        ALBIngressController: !FindInMap [Config, ALBIngressController, Value]
        EKSClusterName: !Ref EKSClusterName
        NodeInstanceFamily: !Ref NodeInstanceFamily
        NodeGroupType: !FindInMap [ Config, NodeGroupType, Value ]
        ClusterAutoScaler: Enabled
  NvidiaDevicePlugin:
    Type: AWS::CloudFormation::Stack
    Condition: DeployNvidiaPlugin
    DependsOn: EKSNewVPC
    Properties:
      TemplateURL: !Sub
        - 'https://${QSS3BucketName}.s3.${QSS3BucketRegion}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/nvidia-device-plugin.template.yaml'
        - QSS3BucketName: !FindInMap [ Config, QSS3BucketName, Value ]
          QSS3BucketRegion: !FindInMap [ Config, QSS3BucketRegion, Value ]
          QSS3KeyPrefix: !FindInMap [ Config, QSS3KeyPrefix, Value ]
      Parameters:
        EKSClusterName: !Ref EKSClusterName
  MLRunKit:
    Type: AWS::CloudFormation::Stack
    Condition: DeployMLRunStack
    DependsOn: EKSNewVPC
    Properties:
      TemplateURL: !Sub
        - 'https://${QSS3BucketName}.s3.${QSS3BucketRegion}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/mlrun-kit.template.yaml'
        - QSS3BucketName: !FindInMap [ Config, QSS3BucketName, Value ]
          QSS3BucketRegion: !FindInMap [ Config, QSS3BucketRegion, Value ]
          QSS3KeyPrefix: !FindInMap [ Config, QSS3KeyPrefix, Value ]
      Parameters:
        EKSClusterName: !Ref EKSClusterName
        ClusterDomain: !Ref ClusterDomain
        RegistryDomainName: !Ref RegistryDomainName
        RegistrySuffix: !Ref RegistrySuffix
        RegistryUsername: !Ref RegistryUsername
        RegistryPassword: !Ref RegistryPassword
        RegistryEmail: !Ref RegistryEmail
        MLrunKitVersion: !Ref MLrunKitVersion
        OIDCProvider: !Join [ '', !Split [ 'https://', !GetAtt EKSNewVPC.Outputs.OIDCIssuerURL ] ]
Outputs:
  BastionIP:
    Value: !GetAtt EKSNewVPC.Outputs.BastionIP
  EKSClusterName:
    Description: "This is the name of your EKS cluster"
    Value: !GetAtt EKSNewVPC.Outputs.EKSClusterName
  KubeConfig:
    Description: "Run this command in your terminal to get access to your EKS cluster"
    Value: !Sub aws eks update-kubeconfig --name=${EKSClusterName}
  JupyterNotebook:
    Value: !GetAtt MLRunKit.Outputs.JupyterNotebook
    Condition: DeployMLRunStack
  MLRunUI:
    Value: !GetAtt MLRunKit.Outputs.MLRunUI
    Condition: DeployMLRunStack
  MLRunAPI:
    Value: !GetAtt MLRunKit.Outputs.MLRunAPI
    Condition: DeployMLRunStack
  Nuclio:
    Value: !GetAtt MLRunKit.Outputs.Nuclio
    Condition: DeployMLRunStack


